# Generated by Django 4.2.28 on 2026-02-04 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstanciaProcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(help_text='Gerado automaticamente (ex: TEF-2026-001)', max_length=50, unique=True, verbose_name='Número do Processo')),
                ('dados', models.JSONField(default=dict, help_text='Dados dinâmicos do formulário armazenados em JSON', verbose_name='Dados do Formulário')),
                ('origem', models.CharField(choices=[('formulario_externo', 'Formulário Externo'), ('criacao_interna', 'Criação Interna')], default='criacao_interna', max_length=20, verbose_name='Origem')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('criado_por', models.ForeignKey(blank=True, help_text='Usuário que criou o processo (null se criado via formulário externo)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processos_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado Por')),
                ('fase_atual', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processos_nesta_fase', to='core.fase', verbose_name='Fase Atual')),
                ('responsavel_atual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processos_responsavel', to=settings.AUTH_USER_MODEL, verbose_name='Responsável Atual')),
                ('tipo_processo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instancias', to='core.tipoprocesso', verbose_name='Tipo de Processo')),
            ],
            options={
                'verbose_name': 'Processo',
                'verbose_name_plural': 'Processos',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['tipo_processo', 'fase_atual'], name='processos_i_tipo_pr_097a10_idx'), models.Index(fields=['responsavel_atual'], name='processos_i_respons_8e3b6f_idx'), models.Index(fields=['-criado_em'], name='processos_i_criado__8745ad_idx')],
            },
        ),
    ]
