# Generated by Django 4.2.28 on 2026-02-04 19:05

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoProcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Credenciamento TEF/PIX', max_length=200, unique=True, verbose_name='Nome do Processo')),
                ('descricao', models.TextField(help_text='Descrição detalhada do processo', verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, help_text='Processos inativos não podem receber novas solicitações', verbose_name='Ativo')),
                ('prefixo_numero', models.CharField(help_text='Prefixo para numeração automática (ex: TEF, SUP, FIN)', max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Apenas letras maiúsculas', regex='^[A-Z]+$')], verbose_name='Prefixo do Número')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Tipo de Processo',
                'verbose_name_plural': 'Tipos de Processos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Fase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Novas Solicitações, Cadastro Interno', max_length=200, verbose_name='Nome da Fase')),
                ('ordem', models.IntegerField(help_text='Ordem sequencial da fase no workflow (1, 2, 3...)', verbose_name='Ordem')),
                ('setor_responsavel', models.CharField(choices=[('COMERCIAL', 'Comercial'), ('FINANCEIRO', 'Financeiro'), ('OPERACOES', 'Operações'), ('PD', 'P&D'), ('ADMIN', 'Administrativo'), ('TODOS', 'Todos os Setores')], help_text='Setor responsável por esta fase', max_length=20, verbose_name='Setor Responsável')),
                ('permite_avancar', models.BooleanField(default=True, help_text='Permite avançar para a próxima fase', verbose_name='Permite Avançar')),
                ('permite_retornar', models.BooleanField(default=True, help_text='Permite retornar para fase anterior', verbose_name='Permite Retornar')),
                ('fase_inicial', models.BooleanField(default=False, help_text='Marca como fase inicial do processo (criação via formulário externo)', verbose_name='Fase Inicial')),
                ('fase_final', models.BooleanField(default=False, help_text='Marca como fase de conclusão do processo', verbose_name='Fase Final')),
                ('cor_badge', models.CharField(default='#6c757d', help_text='Cor hexadecimal para exibição (ex: #007bff)', max_length=7, verbose_name='Cor do Badge')),
                ('tipo_processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fases', to='core.tipoprocesso', verbose_name='Tipo de Processo')),
                ('usuarios_autorizados', models.ManyToManyField(blank=True, help_text='Usuários específicos autorizados (deixe vazio para permitir todo o setor)', related_name='fases_autorizadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuários Autorizados')),
            ],
            options={
                'verbose_name': 'Fase',
                'verbose_name_plural': 'Fases',
                'ordering': ['tipo_processo', 'ordem'],
                'unique_together': {('tipo_processo', 'ordem'), ('tipo_processo', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='CampoFormulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_campo', models.CharField(help_text='Nome técnico do campo (sem espaços, ex: cnpj_empresa)', max_length=100, validators=[django.core.validators.RegexValidator(message='Use apenas letras minúsculas, números e underscore. Deve começar com letra.', regex='^[a-z][a-z0-9_]*$')], verbose_name='Nome do Campo')),
                ('label', models.CharField(help_text='Texto exibido para o usuário (ex: CNPJ da Empresa)', max_length=200, verbose_name='Rótulo')),
                ('tipo_campo', models.CharField(choices=[('text', 'Texto Curto'), ('textarea', 'Texto Longo'), ('number', 'Número'), ('email', 'E-mail'), ('tel', 'Telefone'), ('date', 'Data'), ('select', 'Seleção (Dropdown)'), ('radio', 'Seleção (Radio)'), ('checkbox', 'Múltipla Escolha'), ('file', 'Arquivo')], max_length=20, verbose_name='Tipo de Campo')),
                ('opcoes', models.JSONField(blank=True, help_text='Para campos select/radio/checkbox. Ex: ["Opção 1", "Opção 2"] ou [{"value": "1", "label": "Opção 1"}]', null=True, verbose_name='Opções')),
                ('obrigatorio', models.BooleanField(default=False, help_text='Campo obrigatório em todas as fases', verbose_name='Obrigatório')),
                ('ordem', models.IntegerField(default=0, help_text='Ordem de exibição do campo', verbose_name='Ordem')),
                ('grupo', models.CharField(blank=True, help_text='Agrupa campos visualmente (ex: Dados da Empresa, Dados TEF)', max_length=100, verbose_name='Grupo')),
                ('ajuda', models.TextField(blank=True, help_text='Texto de ajuda exibido abaixo do campo', verbose_name='Texto de Ajuda')),
                ('validacao_regex', models.CharField(blank=True, help_text='Expressão regular para validação customizada', max_length=500, verbose_name='Validação (Regex)')),
                ('placeholder', models.CharField(blank=True, help_text='Texto de exemplo dentro do campo', max_length=200, verbose_name='Placeholder')),
                ('visivel_formulario_externo', models.BooleanField(default=True, help_text='Se desmarcado, o campo só aparece internamente', verbose_name='Visível no Formulário Externo')),
                ('obrigatorio_em_fases', models.ManyToManyField(blank=True, help_text='Fases onde este campo é obrigatório', related_name='campos_obrigatorios', to='core.fase', verbose_name='Obrigatório nas Fases')),
                ('tipo_processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campos', to='core.tipoprocesso', verbose_name='Tipo de Processo')),
            ],
            options={
                'verbose_name': 'Campo do Formulário',
                'verbose_name_plural': 'Campos do Formulário',
                'ordering': ['tipo_processo', 'grupo', 'ordem'],
                'unique_together': {('tipo_processo', 'nome_campo')},
            },
        ),
    ]
