# Generated by Django 4.2.28 on 2026-02-04 19:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormularioExterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=uuid.uuid4, editable=False, help_text='Token único para acesso ao formulário', max_length=100, unique=True, verbose_name='Token')),
                ('ativo', models.BooleanField(default=True, help_text='Formulários inativos não aceitam novas submissões', verbose_name='Ativo')),
                ('titulo', models.CharField(help_text='Título exibido no formulário externo', max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(help_text='Texto de introdução exibido no formulário', verbose_name='Descrição')),
                ('mensagem_sucesso', models.TextField(default='Sua solicitação foi enviada com sucesso! Em breve entraremos em contato.', help_text='Mensagem exibida após envio bem-sucedido', verbose_name='Mensagem de Sucesso')),
                ('cor_tema', models.CharField(default='#0066cc', help_text='Cor principal do formulário (hexadecimal)', max_length=7, verbose_name='Cor do Tema')),
                ('logo_url', models.URLField(blank=True, help_text='URL da logo a ser exibida no formulário', verbose_name='URL da Logo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('tipo_processo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='formulario_externo', to='core.tipoprocesso', verbose_name='Tipo de Processo')),
            ],
            options={
                'verbose_name': 'Formulário Externo',
                'verbose_name_plural': 'Formulários Externos',
                'ordering': ['tipo_processo__nome'],
            },
        ),
    ]
