# Generated by Django 4.2.28 on 2026-02-04 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('processos', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoProcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('criacao', 'Criação do Processo'), ('mudanca_fase', 'Mudança de Fase'), ('edicao_dados', 'Edição de Dados'), ('atribuicao', 'Atribuição de Responsável'), ('comentario', 'Comentário')], max_length=20, verbose_name='Tipo de Evento')),
                ('observacoes', models.TextField(blank=True, help_text='Comentários ou observações sobre a ação', verbose_name='Observações')),
                ('dados_alterados', models.JSONField(blank=True, help_text='Snapshot das alterações realizadas', null=True, verbose_name='Dados Alterados')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora')),
                ('fase_anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historico_fase_anterior', to='core.fase', verbose_name='Fase Anterior')),
                ('fase_nova', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historico_fase_nova', to='core.fase', verbose_name='Fase Nova')),
                ('instancia_processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='processos.instanciaprocesso', verbose_name='Processo')),
                ('usuario', models.ForeignKey(blank=True, help_text='Usuário que realizou a ação (null se ação automática)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historico_acoes', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Histórico do Processo',
                'verbose_name_plural': 'Histórico dos Processos',
                'ordering': ['-criado_em'],
                'permissions': [],
                'indexes': [models.Index(fields=['instancia_processo', '-criado_em'], name='auditoria_h_instanc_9f911b_idx'), models.Index(fields=['tipo_evento'], name='auditoria_h_tipo_ev_144b3e_idx')],
            },
        ),
    ]
